[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 1000000
via_ir = true

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
sepolia = "https://rpc.sepolia.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
